### ISSUE TITLE
BEAR usage on 4 chloroplast genomes

### ISSUE THREAD

**Issue by agroppi** [solonas13/bear#1]
I have 4 new assembled chloroplast genomes (~160 kb each)
My goal is to perform a phylogeny analysis on these 4 sequences.
After the assembly, the sequences are not starting at the same point (in respect to the general chloroplast genome structure)
That's why I tried to use BEAR to "synchronize" all the 4 sequences at the same starting point.
1/ Do I understand the features of BEAR ? Does it exactly what I want to do?
2/ I tried also to use MARS (https://github.com/lorrainea/MARS/issues/5)
Does MARS have the same function as BEAR ?
In BEAR option d0 and d1 give different results.
3/ What would be the best tool and the right option to perform what I wish ? : 

4 sequences (multifasta) ==> BEAR ==> MAFFT multiple alignement ==> Phyml (phylogenic tree construction)

**Comment by solonas13** [comment]
Hi Alexis,

MARS is generally more accurate than BEAR and so only MARS is actively maintained. I will thus respond to your message using the MARS github.

--Solon
